"""
Agentica P18: Architecture Decision Record (ADR) Generator
Converts a Simulacrum session JSON into a permanent, professional ADR document.
Secretary Bird: documents every stomp for the historical record. 🦅

Usage:
  python scripts/adr_generator.py session_d1a3705f.json
  python scripts/adr_generator.py --latest
  python scripts/adr_generator.py --list
"""
import json
import sys
import io
from datetime import datetime
from pathlib import Path

if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

GREEN  = "\033[92m"
YELLOW = "\033[93m"
BOLD   = "\033[1m"
RESET  = "\033[0m"

ADR_DIR = Path("docs/decisions")
SIMULACRUM_LOG_DIR = Path(".Agentica/logs/simulacrum")


def load_session(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def get_next_adr_number() -> int:
    ADR_DIR.mkdir(parents=True, exist_ok=True)
    existing = sorted(ADR_DIR.glob("ADR-*.md"))
    if not existing:
        return 1
    last = existing[-1].stem  # e.g. ADR-007
    return int(last.split("-")[1]) + 1


def generate_adr(session: dict) -> str:
    """Generate a professional ADR markdown document from a simulacrum session."""
    adr_num = get_next_adr_number()
    topic    = session.get("topic", "Untitled Decision")
    agents   = session.get("agents", [])
    session_id = session.get("session_id", "unknown")
    timestamp  = session.get("timestamp", datetime.now().isoformat())
    mode       = session.get("mode", "PERSONA_FALLBACK")
    win_agent  = session.get("winning_agent", "unknown")
    win_prop   = session.get("winning_proposal", "")
    vote_tally = session.get("vote_tally", {})
    proposals  = session.get("all_proposals", {})
    transcript = session.get("transcript", [])
    constraints = session.get("constraints", [])

    # Format date
    try:
        dt = datetime.fromisoformat(timestamp)
        date_str = dt.strftime("%Y-%m-%d")
    except Exception:
        date_str = timestamp[:10]

    # Build context from opening positions in transcript
    context_lines = [
        e["content"] for e in transcript
        if e.get("phase") == "opening"
    ]

    # Build consequences from proposals
    consequences = [
        f"- **{agent}** proposed: {prop[:120]}"
        for agent, prop in proposals.items()
    ]

    # Build vote summary
    vote_lines = [
        f"| {agent} | {votes} vote(s) | {'WINNER' if agent == win_agent else ''} |"
        for agent, votes in sorted(vote_tally.items(), key=lambda x: -x[1])
    ]

    adr = f"""# ADR-{adr_num:03d}: {topic}

| Field | Value |
|---|---|
| **Status** | Accepted |
| **Date** | {date_str} |
| **Session** | Simulacrum `{session_id}` |
| **Mode** | {mode} |
| **Decided by** | {', '.join(agents)} |

---

## Context

{topic}

This decision was reached through an automated **Logic Simulacrum** session where specialist agents debated the topic from their respective domain perspectives.

### Participating Agents
{chr(10).join(f'- `{a}`' for a in agents)}

### Opening Positions
{chr(10).join(f'- **{e["speaker"]}**: {e["content"][:200]}' for e in transcript if e.get("phase") == "opening")}

---

## Decision

**Winning approach** (proposed by `{win_agent}`, {vote_tally.get(win_agent, 0)} vote(s)):

> {win_prop}

---

## Alternatives Considered

{chr(10).join(consequences)}

### Vote Summary

| Agent | Votes | Status |
|---|---|---|
{chr(10).join(vote_lines)}

---

## Consequences

### Constraints Agreed Upon
{chr(10).join(f'- `{a}`: focus on {p[:100]}' for a, p in proposals.items()) if proposals else '- None specified'}

### Implementation Notes
- This decision was reached by consensus of all participating agents.
- The winning approach must be implemented respecting all agent constraints listed above.
- Any deviation from this ADR requires a new Simulacrum session.

---

## References

- Simulacrum session log: `.Agentica/logs/simulacrum/session_{session_id}.json`
- Generated by: `Agentica P18 ADR Generator`
- Secretary Bird System v5.0 🦅

---
*This ADR was automatically generated from an AI agent debate. Human review recommended.*
"""
    return adr_num, adr


def save_adr(adr_num: int, content: str, topic: str) -> Path:
    ADR_DIR.mkdir(parents=True, exist_ok=True)
    # Create a slug from the topic
    slug = "-".join(topic.lower().split()[:6])
    slug = "".join(c if c.isalnum() or c == "-" else "" for c in slug)
    path = ADR_DIR / f"ADR-{adr_num:03d}-{slug[:40]}.md"
    path.write_text(content, encoding="utf-8")
    return path


def list_sessions() -> list[Path]:
    if not SIMULACRUM_LOG_DIR.exists():
        return []
    return sorted(SIMULACRUM_LOG_DIR.glob("session_*.json"), reverse=True)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="P18: ADR Generator from Simulacrum sessions")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("session", nargs="?", help="Session JSON filename or path")
    group.add_argument("--latest", action="store_true", help="Use the most recent session")
    group.add_argument("--list", action="store_true", help="List all available sessions")
    parser.add_argument("--all", dest="generate_all", action="store_true",
                        help="Generate ADRs for all sessions")
    args = parser.parse_args()

    if args.list:
        sessions = list_sessions()
        if not sessions:
            print(f"{YELLOW}No sessions found in {SIMULACRUM_LOG_DIR}{RESET}")
        else:
            print(f"\n{BOLD}Available Simulacrum Sessions:{RESET}")
            for s in sessions:
                data = json.loads(s.read_text(encoding="utf-8"))
                print(f"  {s.name}  |  {data.get('topic', '?')[:60]}")
        sys.exit(0)

    if args.generate_all:
        sessions = list_sessions()
        generated = []
        for s in sessions:
            session = load_session(s)
            num, content = generate_adr(session)
            path = save_adr(num, content, session.get("topic", "decision"))
            generated.append(path)
            print(f"{GREEN}Generated: {path}{RESET}")
        print(f"\n{BOLD}Generated {len(generated)} ADRs in {ADR_DIR}/{RESET}")
        sys.exit(0)

    if args.latest:
        sessions = list_sessions()
        if not sessions:
            print(f"{YELLOW}No sessions found.{RESET}")
            sys.exit(1)
        session_path = sessions[0]
    elif args.session:
        p = Path(args.session)
        if not p.exists():
            p = SIMULACRUM_LOG_DIR / args.session
        if not p.exists():
            print(f"Session not found: {args.session}")
            sys.exit(1)
        session_path = p
    else:
        parser.print_help()
        sys.exit(0)

    session  = load_session(session_path)
    num, content = generate_adr(session)
    path = save_adr(num, content, session.get("topic", "decision"))

    print(f"\n{GREEN}{BOLD}ADR-{num:03d} Generated:{RESET}")
    print(f"  File: {path}")
    print(f"  Topic: {session.get('topic', '?')[:70]}")
    print(f"  Winner: {session.get('winning_agent', '?')}")
    print(f"\n{BOLD}Preview:{RESET}")
    print("\n".join(content.splitlines()[:20]))
